### ISSUE TITLE
Correct the OpenMP runtime checks if the data is already mapped to avoid unnecessary data movement.

### ISSUE THREAD

**Issue by jycheng1989** [naromero77/ACC2OMP#15]
'acc update host' should be converted to 'omp target update from'

'acc update device' should be converted to 'omp target update to'

'$acc wait' should be '$omp taskwait',

which is missing in the script,

'$acc .... present(...)' should be '$omp ... map(...)'

which is omitted by default.

You can look at the sourcecode at 
https://github.com/jycheng1989/GEM-parallel-coupling.git
the '**openmp_target** ' branch.

**Comment by naromero77** [comment]
> 'acc update host' should be converted to 'omp target update from'
> 
> 'acc update device' should be converted to 'omp target update to'
These two got implemented.

> 
> '$acc wait' should be '$omp taskwait',
> 
> which is missing in the script,
I think the way to do this is to do a `$omp <directives> nowait`, followed later by `$omp taskwait` later on in the program. The Python parser is simple and cannot handle this at the moment.

> 
> '$acc .... present(...)' should be '$omp ... map(...)'
> 
> which is omitted by default.
I am not sure that this is the right thing to do. I thought I read somewhere that OpenMP spec may include a `present` clause in the future which would be the right mapping IMO.

> 
> You can look at the sourcecode at
> https://github.com/jycheng1989/GEM-parallel-coupling.git
> the '**openmp_target** ' branch.
